// Additional Features and Enhancements

// Export Functions for Admin Dashboard
function exportStudentsCSV() {
    const students = DataManager.getStudents();
    const exportData = students.map(s => ({
        'Student ID': s.studentId,
        'Name': s.name,
        'Email': s.email,
        'Phone': s.phone || 'N/A',
        'Joined': UIHelper.formatDate(s.createdAt)
    }));
    DataExport.toCSV(exportData, 'students.csv');
}

function exportBooksCSV() {
    const books = DataManager.getBooks();
    const exportData = books.map(b => ({
        'Title': b.title,
        'Author': b.author,
        'ISBN': b.isbn,
        'Category': b.category,
        'Total': b.quantity,
        'Available': b.available
    }));
    DataExport.toCSV(exportData, 'books.csv');
}

function exportBorrowingCSV() {
    const borrowing = JSON.parse(localStorage.getItem('borrowing') || '[]');
    const students = DataManager.getStudents();
    const books = DataManager.getBooks();
    
    const exportData = borrowing.map(b => ({
        'Student': students.find(s => s.id === b.studentId)?.name || 'Unknown',
        'Book': books.find(k => k.id === b.bookId)?.title || 'Unknown',
        'Issue Date': UIHelper.formatDate(b.issuedDate),
        'Due Date': UIHelper.formatDate(b.dueDate),
        'Returned': b.returnedDate ? UIHelper.formatDate(b.returnedDate) : 'Not Returned'
    }));
    DataExport.toCSV(exportData, 'borrowing_records.csv');
}

function exportStudentsJSON() {
    const students = DataManager.getStudents();
    DataExport.toJSON(students, 'students.json');
}

function exportBooksJSON() {
    const books = DataManager.getBooks();
    DataExport.toJSON(books, 'books.json');
}

// Print Functions
function printStudentsTable() {
    PrintHelper.printTable('students-table', 'Student List');
}

function printBooksTable() {
    PrintHelper.printTable('books-table', 'Library Books');
}

function printBorrowingTable() {
    PrintHelper.printTable('borrowed-table', 'Borrowing Records');
}

function printBorrowingReport() {
    const currentUser = JSON.parse(localStorage.getItem('currentUser'));
    const borrowing = JSON.parse(localStorage.getItem('borrowing') || '[]');
    const students = DataManager.getStudents();
    const books = DataManager.getBooks();

    const printWindow = window.open('', '', 'height=600,width=900');
    const reportHTML = `
        <html>
            <head>
                <title>Borrowing Report</title>
                <style>
                    body { font-family: Arial, sans-serif; margin: 20px; }
                    h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
                    h2 { color: #34495e; margin-top: 20px; }
                    .info { background: #f9f9f9; padding: 10px; margin: 10px 0; border-left: 4px solid #3498db; }
                    table { border-collapse: collapse; width: 100%; margin-top: 15px; }
                    th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
                    th { background-color: #2c3e50; color: white; }
                    tr:nth-child(even) { background-color: #f9f9f9; }
                    .summary { margin-top: 20px; }
                    .stat { display: inline-block; margin-right: 30px; }
                    .stat-value { font-size: 24px; font-weight: bold; color: #3498db; }
                </style>
            </head>
            <body>
                <h1>📊 Library Borrowing Report</h1>
                <div class="info">
                    <strong>Generated by:</strong> ${currentUser.name}<br>
                    <strong>Report Date:</strong> ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                </div>

                <h2>Borrowing Statistics</h2>
                <div class="summary">
                    <div class="stat">
                        <div>Total Borrowed</div>
                        <div class="stat-value">${borrowing.length}</div>
                    </div>
                    <div class="stat">
                        <div>Currently Borrowed</div>
                        <div class="stat-value">${borrowing.filter(b => !b.returnedDate).length}</div>
                    </div>
                    <div class="stat">
                        <div>Returned</div>
                        <div class="stat-value">${borrowing.filter(b => b.returnedDate).length}</div>
                    </div>
                </div>

                <h2>Current Borrowed Books</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Student</th>
                            <th>Book</th>
                            <th>Issue Date</th>
                            <th>Due Date</th>
                            <th>Days Remaining</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${borrowing.filter(b => !b.returnedDate).map(b => {
                            const student = students.find(s => s.id === b.studentId);
                            const book = books.find(k => k.id === b.bookId);
                            const daysLeft = Math.ceil((new Date(b.dueDate) - new Date()) / (1000 * 60 * 60 * 24));
                            return `
                                <tr>
                                    <td>${student?.name || 'Unknown'}</td>
                                    <td>${book?.title || 'Unknown'}</td>
                                    <td>${UIHelper.formatDate(b.issuedDate)}</td>
                                    <td>${UIHelper.formatDate(b.dueDate)}</td>
                                    <td style="color: ${daysLeft < 0 ? 'red' : 'green'}; font-weight: bold;">
                                        ${daysLeft < 0 ? 'OVERDUE (' + Math.abs(daysLeft) + ' days)' : daysLeft + ' days'}
                                    </td>
                                </tr>
                            `;
                        }).join('')}
                    </tbody>
                </table>
            </body>
        </html>
    `;
    printWindow.document.write(reportHTML);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 250);
}

// Advanced Statistics Functions
function generateLibraryStats() {
    const borrowing = JSON.parse(localStorage.getItem('borrowing') || '[]');
    const books = DataManager.getBooks();
    const students = DataManager.getStudents();
    const today = new Date();

    const stats = {
        totalBooks: books.length,
        totalAvailable: books.reduce((sum, b) => sum + b.available, 0),
        totalBorrowed: books.reduce((sum, b) => sum + (b.quantity - b.available), 0),
        totalStudents: students.length,
        totalBorrows: borrowing.length,
        currentlyBorrowed: borrowing.filter(b => !b.returnedDate).length,
        returned: borrowing.filter(b => b.returnedDate).length,
        overdue: borrowing.filter(b => !b.returnedDate && new Date(b.dueDate) < today).length,
        dueSoon: borrowing.filter(b => {
            if (b.returnedDate) return false;
            const daysLeft = Math.ceil((new Date(b.dueDate) - today) / (1000 * 60 * 60 * 24));
            return daysLeft > 0 && daysLeft <= 3;
        }).length
    };

    return stats;
}

// Category Statistics
function getCategoryStats() {
    const books = DataManager.getBooks();
    const categories = {};

    books.forEach(book => {
        if (!categories[book.category]) {
            categories[book.category] = { total: 0, available: 0 };
        }
        categories[book.category].total++;
        categories[book.category].available += book.available;
    });

    return Object.entries(categories).map(([name, stats]) => ({
        name,
        total: stats.total,
        available: stats.available,
        borrowed: stats.total - stats.available
    }));
}

// Student Activity Statistics
function getStudentActivityStats(studentId) {
    const borrowing = JSON.parse(localStorage.getItem('borrowing') || '[]');
    const studentBorrows = borrowing.filter(b => b.studentId === studentId);

    return {
        totalBorrowed: studentBorrows.length,
        currentlyBorrowed: studentBorrows.filter(b => !b.returnedDate).length,
        returned: studentBorrows.filter(b => b.returnedDate).length,
        overdue: studentBorrows.filter(b => !b.returnedDate && new Date(b.dueDate) < new Date()).length
    };
}

// Bulk Operations
function bulkDeleteStudents(studentIds) {
    if (confirm(`Are you sure you want to delete ${studentIds.length} students?`)) {
        const students = DataManager.getStudents();
        const filtered = students.filter(s => !studentIds.includes(s.id));
        localStorage.setItem('students', JSON.stringify(filtered));
        UIHelper.showSuccess(`${studentIds.length} students deleted`);
        loadStudentsTable();
        return true;
    }
    return false;
}

function bulkDeleteBooks(bookIds) {
    if (confirm(`Are you sure you want to delete ${bookIds.length} books?`)) {
        const books = DataManager.getBooks();
        const filtered = books.filter(b => !bookIds.includes(b.id));
        localStorage.setItem('books', JSON.stringify(filtered));
        UIHelper.showSuccess(`${bookIds.length} books deleted`);
        loadBooksTable();
        return true;
    }
    return false;
}

// Bulk Update
function bulkUpdateBookCategory(bookIds, newCategory) {
    const books = DataManager.getBooks();
    bookIds.forEach(id => {
        const book = books.find(b => b.id === id);
        if (book) {
            book.category = newCategory;
        }
    });
    localStorage.setItem('books', JSON.stringify(books));
    UIHelper.showSuccess(`${bookIds.length} books category updated`);
    loadBooksTable();
}

// Search and Advanced Filtering
function advancedSearch(filters) {
    let results = {
        students: DataManager.getStudents(),
        books: DataManager.getBooks()
    };

    if (filters.studentName) {
        results.students = SearchFilter.searchStudents(filters.studentName);
    }

    if (filters.bookTitle) {
        results.books = SearchFilter.searchBooks(filters.bookTitle);
    }

    if (filters.category) {
        results.books = results.books.filter(b => b.category === filters.category);
    }

    if (filters.availableOnly) {
        results.books = results.books.filter(b => b.available > 0);
    }

    return results;
}

// Notification Management
function getAdminNotifications() {
    const notifications = NotificationCenter.getPendingNotifications();
    return notifications;
}

function clearNotifications() {
    const container = document.getElementById('notifications-list');
    if (container) {
        container.innerHTML = '<p class="text-center">No pending notifications</p>';
    }
    UIHelper.showSuccess('Notifications cleared');
}

// System Health Check
function getSystemHealthStatus() {
    const students = DataManager.getStudents();
    const books = DataManager.getBooks();
    const borrowing = JSON.parse(localStorage.getItem('borrowing') || '[]');
    const admins = JSON.parse(localStorage.getItem('admins') || '[]');

    return {
        status: 'healthy',
        dataSize: {
            students: students.length,
            books: books.length,
            borrowing: borrowing.length,
            admins: admins.length
        },
        storageUsage: `${(JSON.stringify(localStorage).length / 1024).toFixed(2)} KB`,
        lastBackup: localStorage.getItem('lastBackup') || 'Never',
        totalUsers: students.length + admins.length
    };
}

// Backup System Data
function backupSystemData() {
    const backup = {
        students: DataManager.getStudents(),
        books: DataManager.getBooks(),
        borrowing: JSON.parse(localStorage.getItem('borrowing') || '[]'),
        admins: JSON.parse(localStorage.getItem('admins') || '[]'),
        ebooks: JSON.parse(localStorage.getItem('ebooks') || '[]'),
        categories: JSON.parse(localStorage.getItem('categories') || '[]'),
        backupDate: new Date().toISOString()
    };

    DataExport.toJSON(backup, `library_backup_${new Date().getTime()}.json`);
    localStorage.setItem('lastBackup', new Date().toISOString());
    UIHelper.showSuccess('System backup created successfully');
}

// Restore System Data
function restoreFromBackup(backupData) {
    try {
        localStorage.setItem('students', JSON.stringify(backupData.students));
        localStorage.setItem('books', JSON.stringify(backupData.books));
        localStorage.setItem('borrowing', JSON.stringify(backupData.borrowing));
        localStorage.setItem('admins', JSON.stringify(backupData.admins));
        localStorage.setItem('ebooks', JSON.stringify(backupData.ebooks));
        localStorage.setItem('categories', JSON.stringify(backupData.categories));
        UIHelper.showSuccess('System restored from backup');
        location.reload();
    } catch (e) {
        UIHelper.showError('Failed to restore backup: ' + e.message);
    }
}

// User Activity Logging
function logActivity(action, details) {
    const currentUser = JSON.parse(localStorage.getItem('currentUser'));
    const activityLog = JSON.parse(localStorage.getItem('activityLog') || '[]');

    activityLog.push({
        timestamp: new Date().toISOString(),
        user: currentUser.name,
        action,
        details
    });

    localStorage.setItem('activityLog', JSON.stringify(activityLog));
}

// Get Activity Log
function getActivityLog(limit = 50) {
    const log = JSON.parse(localStorage.getItem('activityLog') || '[]');
    return log.slice(-limit).reverse();
}

// Email Simulation
function simulateSendEmail(to, subject, body) {
    logActivity('Email Sent', { to, subject });
    
    const emails = JSON.parse(localStorage.getItem('sentEmails') || '[]');
    emails.push({
        id: Date.now().toString(),
        to,
        subject,
        body,
        sentAt: new Date().toISOString(),
        status: 'sent'
    });

    localStorage.setItem('sentEmails', JSON.stringify(emails));
    return true;
}

// Send Bulk Emails
function sendBulkEmails(recipients, subject, template) {
    recipients.forEach(email => {
        simulateSendEmail(email, subject, template);
    });
    UIHelper.showSuccess(`Emails sent to ${recipients.length} recipients`);
}

// Send Overdue Reminders
function sendOverdueReminders() {
    const borrowing = JSON.parse(localStorage.getItem('borrowing') || '[]');
    const students = DataManager.getStudents();
    const books = DataManager.getBooks();
    const today = new Date();

    const overdue = borrowing.filter(b => !b.returnedDate && new Date(b.dueDate) < today);

    overdue.forEach(borrow => {
        const student = students.find(s => s.id === borrow.studentId);
        const book = books.find(b => b.id === borrow.bookId);

        if (student) {
            const daysOverdue = Math.floor((today - new Date(borrow.dueDate)) / (1000 * 60 * 60 * 24));
            const subject = `📚 Overdue Book Reminder - ${book?.title}`;
            const body = `Dear ${student.name},\n\nYour book "${book?.title}" is ${daysOverdue} days overdue. Please return it as soon as possible.\n\nThank you!`;
            
            simulateSendEmail(student.email, subject, body);
        }
    });

    UIHelper.showSuccess(`Overdue reminders sent to ${overdue.length} students`);
    logActivity('Bulk Email', { type: 'overdue_reminders', count: overdue.length });
}

// Export all features
window.exportStudentsCSV = exportStudentsCSV;
window.exportBooksCSV = exportBooksCSV;
window.exportBorrowingCSV = exportBorrowingCSV;
window.printStudentsTable = printStudentsTable;
window.printBooksTable = printBooksTable;
window.printBorrowingTable = printBorrowingTable;
window.printBorrowingReport = printBorrowingReport;
window.generateLibraryStats = generateLibraryStats;
window.getCategoryStats = getCategoryStats;
window.advancedSearch = advancedSearch;
window.getAdminNotifications = getAdminNotifications;
window.backupSystemData = backupSystemData;
window.restoreFromBackup = restoreFromBackup;
window.logActivity = logActivity;
window.sendBulkEmails = sendBulkEmails;
window.sendOverdueReminders = sendOverdueReminders;
